In [32]:
# 1.Padronizar a coluna 'categoria' para minúsculas.

import pandas as pd

df = pd.read_excel('vendas.xlsx') 

df['categoria'] = df['categoria'].str.lower()

df.to_excel('vendas.xlsx', index=False) 

display(df)

PermissionError: [Errno 13] Permission denied: 'vendas.xlsx'

In [ ]:
# 2.Remover registros onde a quantidade está ausente

df = pd.read_excel('vendas.xlsx')

df = df.dropna(subset=['quantidade'])

df.to_excel('vendas.xlsx', index=False)

display(df)

,data,loja,categoria,produto,quantidade,valor_venda
0,2024-07-20,Vento Norte,eletrodomesticos,Aquecedor,5.0,405.55
1,2024-05-30,Vento Norte,sazonal,Guarda-chuva,6.0,2866.20
2,2024-01-25,Vento Norte,roupas,Calça,8.0,3292.72
3,2024-07-10,Chuva Clara,roupas,Casaco,5.0,1294.95
5,2024-08-31,Porto Sol,sazonal,Manta térmica,2.0,957.96
...,...,...,...,...,...,...
495,2024-08-23,Porto Sol,eletrodomesticos,Ventilador,4.0,1545.72
496,2024-12-19,Vento Norte,eletrodomesticos,Ventilador,1.0,230.89
497,2024-05-12,Vila Neve,infantil,Blusa Infantil,6.0,441.30
498,2024-03-08,Vila Neve,eletrodomesticos,Ar-condicionado,1.0,293.93
499,2024-07-25,Vento Norte,sazonal,Guarda-chuva,3.0,1479.81

In [ ]:
# 3. Remover espaços extras e padronizar com primeira letra maiúscula (estilo título)

df['categoria'] = df['categoria'].str.strip()
df['categoria'] = df['categoria'].str.title()

df['produto'] = df['produto'].str.strip()
df['produto'] = df['produto'].str.title()

df['loja'] = df['loja'].str.strip()
df['loja'] = df['loja'].str.title()

display(df)

,data,loja,categoria,produto,quantidade,valor_venda
0,2024-07-20,Vento Norte,Eletrodomesticos,Aquecedor,5.0,405.55
1,2024-05-30,Vento Norte,Sazonal,Guarda-Chuva,6.0,2866.20
2,2024-01-25,Vento Norte,Roupas,Calça,8.0,3292.72
3,2024-07-10,Chuva Clara,Roupas,Casaco,5.0,1294.95
5,2024-08-31,Porto Sol,Sazonal,Manta Térmica,2.0,957.96
...,...,...,...,...,...,...
495,2024-08-23,Porto Sol,Eletrodomesticos,Ventilador,4.0,1545.72
496,2024-12-19,Vento Norte,Eletrodomesticos,Ventilador,1.0,230.89
497,2024-05-12,Vila Neve,Infantil,Blusa Infantil,6.0,441.30
498,2024-03-08,Vila Neve,Eletrodomesticos,Ar-Condicionado,1.0,293.93
499,2024-07-25,Vento Norte,Sazonal,Guarda-Chuva,3.0,1479.81

In [ ]:
# 4. Garantir que a coluna data seja datetime

verificar_tipo = df.select_dtypes(include=['datetime']).columns.to_list()
display(verificar_tipo)

['data']

In [ ]:
# 5. Calcular valor unitário real das vendas válidas

df['valor_unitario'] = df['valor_venda'] / df['quantidade']

display(df)

,data,loja,categoria,produto,quantidade,valor_venda,valor_unitario
0,2024-07-20,Vento Norte,Eletrodomesticos,Aquecedor,5.0,405.55,81.11
1,2024-05-30,Vento Norte,Sazonal,Guarda-Chuva,6.0,2866.20,477.70
2,2024-01-25,Vento Norte,Roupas,Calça,8.0,3292.72,411.59
3,2024-07-10,Chuva Clara,Roupas,Casaco,5.0,1294.95,258.99
5,2024-08-31,Porto Sol,Sazonal,Manta Térmica,2.0,957.96,478.98
...,...,...,...,...,...,...,...
495,2024-08-23,Porto Sol,Eletrodomesticos,Ventilador,4.0,1545.72,386.43
496,2024-12-19,Vento Norte,Eletrodomesticos,Ventilador,1.0,230.89,230.89
497,2024-05-12,Vila Neve,Infantil,Blusa Infantil,6.0,441.30,73.55
498,2024-03-08,Vila Neve,Eletrodomesticos,Ar-Condicionado,1.0,293.93,293.93
499,2024-07-25,Vento Norte,Sazonal,Guarda-Chuva,3.0,1479.81,493.27

In [ ]:
# 6. Calcular valor médio unitário por produto (sem considerar nulos)

df['valor_unitario'] = df['valor_venda'] / df['quantidade']

display(df)

,data,loja,categoria,produto,quantidade,valor_venda,valor_unitario
0,2024-07-20,Vento Norte,Eletrodomesticos,Aquecedor,5.0,405.55,81.11
1,2024-05-30,Vento Norte,Sazonal,Guarda-Chuva,6.0,2866.20,477.70
2,2024-01-25,Vento Norte,Roupas,Calça,8.0,3292.72,411.59
3,2024-07-10,Chuva Clara,Roupas,Casaco,5.0,1294.95,258.99
5,2024-08-31,Porto Sol,Sazonal,Manta Térmica,2.0,957.96,478.98
...,...,...,...,...,...,...,...
495,2024-08-23,Porto Sol,Eletrodomesticos,Ventilador,4.0,1545.72,386.43
496,2024-12-19,Vento Norte,Eletrodomesticos,Ventilador,1.0,230.89,230.89
497,2024-05-12,Vila Neve,Infantil,Blusa Infantil,6.0,441.30,73.55
498,2024-03-08,Vila Neve,Eletrodomesticos,Ar-Condicionado,1.0,293.93,293.93
499,2024-07-25,Vento Norte,Sazonal,Guarda-Chuva,3.0,1479.81,493.27

In [ ]:
# 7. Agrupar e calcular média

media_valor_venda = df['valor_venda'].mean()
media_valor_unitario = df['valor_unitario'].mean()

print(f"Media valor venda: {media_valor_venda:.2f}")
print(f"Media valor unitario: {media_valor_unitario:.2f}")

Media valor venda: 1477.53
Media valor unitario: 274.68

In [ ]:
# 8. Preencher valor_unitario ausente

media = df['valor_unitario'].mean()
df['valor_unitario'] = df['valor_unitario'].fillna(media)

display(df)

,data,loja,categoria,produto,quantidade,valor_venda,valor_unitario
0,2024-07-20,Vento Norte,Eletrodomesticos,Aquecedor,5.0,405.55,81.11
1,2024-05-30,Vento Norte,Sazonal,Guarda-Chuva,6.0,2866.20,477.70
2,2024-01-25,Vento Norte,Roupas,Calça,8.0,3292.72,411.59
3,2024-07-10,Chuva Clara,Roupas,Casaco,5.0,1294.95,258.99
5,2024-08-31,Porto Sol,Sazonal,Manta Térmica,2.0,957.96,478.98
...,...,...,...,...,...,...,...
495,2024-08-23,Porto Sol,Eletrodomesticos,Ventilador,4.0,1545.72,386.43
496,2024-12-19,Vento Norte,Eletrodomesticos,Ventilador,1.0,230.89,230.89
497,2024-05-12,Vila Neve,Infantil,Blusa Infantil,6.0,441.30,73.55
498,2024-03-08,Vila Neve,Eletrodomesticos,Ar-Condicionado,1.0,293.93,293.93
499,2024-07-25,Vento Norte,Sazonal,Guarda-Chuva,3.0,1479.81,493.27

In [ ]:
# 9 - Recalcular valor venda 

df["valor_venda"] = df["quantidade"] * df["valor_unitario"]

display(df)

,data,loja,categoria,produto,quantidade,valor_venda,valor_unitario
0,2024-07-20,Vento Norte,Eletrodomesticos,Aquecedor,5.0,405.55,81.11
1,2024-05-30,Vento Norte,Sazonal,Guarda-Chuva,6.0,2866.20,477.70
2,2024-01-25,Vento Norte,Roupas,Calça,8.0,3292.72,411.59
3,2024-07-10,Chuva Clara,Roupas,Casaco,5.0,1294.95,258.99
5,2024-08-31,Porto Sol,Sazonal,Manta Térmica,2.0,957.96,478.98
...,...,...,...,...,...,...,...
495,2024-08-23,Porto Sol,Eletrodomesticos,Ventilador,4.0,1545.72,386.43
496,2024-12-19,Vento Norte,Eletrodomesticos,Ventilador,1.0,230.89,230.89
497,2024-05-12,Vila Neve,Infantil,Blusa Infantil,6.0,441.30,73.55
498,2024-03-08,Vila Neve,Eletrodomesticos,Ar-Condicionado,1.0,293.93,293.93
499,2024-07-25,Vento Norte,Sazonal,Guarda-Chuva,3.0,1479.81,493.27

In [ ]:
# 10. Salvar o novo DataFrame limpo em um novo arquivo Excel

df.to_excel("vendas.xlsx", index=False)